# EM-TEST Examples

This Jupyter notebook demonstrates how to apply and customize data schema validations on the EM-DAT (Emergency Events Database) xlsx file data using `emtest` together with [`pandas`]() and [`pandera`]() Python packages.

In particular, we will:
1. Load a fake EM-DAT dataset with potential error entries included for the purpose of showcasing data validation techniques.
2. Apply a predefined schema to validate the dataframe, which covers key features in the dataset.
3. Use lazy validation to accumulate all schema errors and present them in a concise report.
Modify the existing data schema, for example by elevating warnings to errors to tighten the accuracy of our data.
4. Demonstrate how to apply specific schemas targeting specific disaster types, such as earthquakes.
5. Customize checks for specific columns in the dataset, reflecting the diversity and complexity of disaster data.

By the end of the notebook, you will have an understanding of integrating pandas with emtest and pandera for validating and looking for potential issues in EM-DAT. 

## Validate the EM-DAT Data

We load the EM-DAT data into and [`pandas.DataFrame`]() and use a pandera 

### Load a fake EM-DAT data

We load a fake EM-DAT dataset that contains 42 errors and 6 warnings and parse it into a `pandas.DataFrame` object. We refer to the "DisNo." column to be used as the index and specify which are the date fields that need to be parsed.

In [1]:
import pandas as pd
import pandera as pa

emdat = pd.read_excel(
    '../data/fake_emdat_test.xlsx',
    index_col='DisNo.',
    parse_dates=['Entry Date', 'Last Update']
)

### Validate with `emdat_schema`

To validate the

In [2]:
from emtest import emdat_schema
emdat_schema.validate(emdat)

C:\Users\dadelforge\Anaconda3\envs\emtest\Lib\site-packages\pandera\backends\pandas\base.py:140: SchemaWarning: Column 'ISO' failed element-wise validator number 1: ISO3 code not in reference list failure cases: wrong_iso, SUN, TWN
  warnings.warn(
C:\Users\dadelforge\Anaconda3\envs\emtest\Lib\site-packages\pandera\backends\pandas\base.py:140: SchemaWarning: Column 'Country' failed element-wise validator number 0: Countries not in reference list failure cases: wrong_country, Soviet Union, Taiwan (Province of China)
  warnings.warn(

SchemaError: Column 'Historic' failed element-wise validator number 0: isin(['Yes', 'No']) failure cases: wrong_historic

### Lazy Validation & Error Reports

In [3]:
try:
    emdat_schema.validate(emdat, lazy=True)
except pa.errors.SchemaErrors as exc:
    print(f"{len(exc.failure_cases)} failure cases:")
    print(exc.failure_cases)
    # use exc.failure_cases.to_csv() method to export

42 failure cases:
   schema_context                                     column  \
41          Index                                     DisNo.
40          Index                                     DisNo.
39          Index                                     DisNo.
30         Column  Reconstruction Costs, Adjusted ('000 US$)
23         Column                                    End Day
24         Column                               Total Deaths
25         Column                                No. Injured
26         Column                               No. Affected
27         Column                               No. Homeless
28         Column                             Total Affected
29         Column            Reconstruction Costs ('000 US$)
32         Column        Insured Damage, Adjusted ('000 US$)
31         Column                  Insured Damage ('000 US$)
1          Column                         Classification Key
33         Column                    Total Damage ('000 US$)
34         Column          Total Damage, Adjusted ('000 US$)
35         Column                                        CPI
36         Column                                Admin Units
37         Column                                 Entry Date
38         Column                                Last Update
22         Column                                  End Month
0          Column                                   Historic
20         Column                                  Start Day
19         Column                                Start Month
2          Column                             Disaster Group
3          Column                          Disaster Subgroup
4          Column                              Disaster Type
5          Column                           Disaster Subtype
6          Column                               External IDs
7          Column                                        ISO
8          Column                                  Subregion
9          Column                                     Region
10         Column                          OFDA/BHA Response
11         Column                                     Appeal
12         Column                                Declaration
13         Column                AID Contribution ('000 US$)
14         Column                                  Magnitude
15         Column                            Magnitude Scale
16         Column                                   Latitude
17         Column                                  Longitude
18         Column                                 Start Year
21         Column                                   End Year

                                                check check_number  \
41                             Invalid DisNo. Pattern            0
40                                   field_uniqueness         None
39                                   field_uniqueness         None
30                                  greater_than(0.0)            0
23                                 isin(range(1, 32))            0
24                                  greater_than(0.0)            0
25                                  greater_than(0.0)            0
26                                  greater_than(0.0)            0
27                                  greater_than(0.0)            0
28                                  greater_than(0.0)            0
29                                  greater_than(0.0)            0
32                                  greater_than(0.0)            0
31                                  greater_than(0.0)            0
1                          Invalid classification key            0
33                                  greater_than(0.0)            0
34                                  greater_than(0.0)            0
35                               in_range(0.0, 100.0)            0
36                                Invalid JSON string            0
37  in_range(1988-01-01 00:00:00, 2024-08-22 12:55...            0
38  in_range(1988-01-01 00:00:00, 2024-08-22 12:55...            0
22                                 isin(range(1, 13))            0
0                                 isin(['Yes', 'No'])            0
20                                 isin(range(1, 32))            0
19                                 isin(range(1, 13))            0
2                                  Invalid group name            0
3                               Invalid subgroup name            0
4                                   Invalid type name            0
5                                Invalid subtype name            0
6                                 Invalid external ID            0
7                                   Invalid ISO3 code            0
8                    Subregions not in reference list            0
9                       Regions not in reference list            0
10                                isin(['Yes', 'No'])            0
11                                isin(['Yes', 'No'])            0
12                                isin(['Yes', 'No'])            0
13                                  greater_than(0.0)            0
14                                  not_equal_to(0.0)            0
15               Magnitude unit not in reference list            0
16                              in_range(-90.0, 90.0)            0
17                            in_range(-180.0, 180.0)            0
18                               in_range(1900, 2024)            0
21                               in_range(1900, 2024)            0

           failure_case          index
41          wrong_disno              0
40        1927-0012-DZA             11
39        1927-0012-DZA              2
30                -10.0  2009-0122-CHN
23                 12.5  1990-0630-IND
24                -10.0  2013-0259-CHN
25                -10.0  2004-0294-FJI
26                -10.0  1983-0440-PAK
27                -10.0  2011-0368-IRN
28                -10.0  2013-0565-CHN
29                -10.0  1990-0508-MEX
32                -10.0  1991-0646-PAK
31                -10.0  1978-0057-ITA
1     wrong_classif_key  1927-0012-DZA
33                -10.0  2005-0639-CHN
34                -10.0  2009-0186-COD
35                101.0  1979-9131-NPL
36           wrong_json  1999-0673-IND
37  1987-01-01 00:00:00  2010-0466-RUS
38  2100-01-01 00:00:00  1993-0500-CMR
22                 -2.0  1998-0261-AUS
0        wrong_historic  1993-0096-DEU
20                 32.0  2002-0492-PNG
19                 13.0  1983-0084-SUN
2           wrong_group  2019-0275-SRB
3        wrong_subgroup  2005-0507-LBR
4            wrong_type  1987-0076-UGA
5         wrong_subtype  1993-0292-PHL
6              wrong_id  2002-0231-MYS
7             wrong_iso  2011-0120-COL
8       wrong_subregion  2003-0608-UKR
9          wrong_region  1927-0012-DZA
10       wrong_response  2019-0008-BRA
11         wrong_appeal  2015-0525-IRL
12    wrong_declaration  2004-0285-IRN
13               -500.0  2021-0649-SVN
14                  0.0  2007-0092-LTU
15           wrong_unit  1995-0192-GLP
16                 91.0  1993-0287-IDN
17                181.0  2018-0091-MOZ
18                 1899  2019-0523-IDN
21                 2100  1981-0106-LKA

C:\Users\dadelforge\Anaconda3\envs\emtest\Lib\site-packages\pandera\backends\pandas\base.py:140: SchemaWarning: Column 'ISO' failed element-wise validator number 1: ISO3 code not in reference list failure cases: wrong_iso, SUN, TWN
  warnings.warn(
C:\Users\dadelforge\Anaconda3\envs\emtest\Lib\site-packages\pandera\backends\pandas\base.py:140: SchemaWarning: Column 'Country' failed element-wise validator number 0: Countries not in reference list failure cases: wrong_country, Soviet Union, Taiwan (Province of China)
  warnings.warn(

In [6]:
from emtest.utils import get_validation_report
get_validation_report(emdat, emdat_schema)

C:\Users\dadelforge\Anaconda3\envs\emtest\Lib\site-packages\pandera\backends\pandas\base.py:140: SchemaWarning: Column 'ISO' failed element-wise validator number 1: ISO3 code not in reference list failure cases: wrong_iso, SUN, TWN
  warnings.warn(
C:\Users\dadelforge\Anaconda3\envs\emtest\Lib\site-packages\pandera\backends\pandas\base.py:140: SchemaWarning: Column 'Country' failed element-wise validator number 0: Countries not in reference list failure cases: wrong_country, Soviet Union, Taiwan (Province of China)
  warnings.warn(

,schema_context,column,check,check_number,failure_case,index
41,Index,DisNo.,Invalid DisNo. Pattern,0,wrong_disno,0
40,Index,DisNo.,field_uniqueness,None,1927-0012-DZA,11
39,Index,DisNo.,field_uniqueness,None,1927-0012-DZA,2
30,Column,"Reconstruction Costs, Adjusted ('000 US$)",greater_than(0.0),0,-10.0,2009-0122-CHN
23,Column,End Day,"isin(range(1, 32))",0,12.5,1990-0630-IND
24,Column,Total Deaths,greater_than(0.0),0,-10.0,2013-0259-CHN
25,Column,No. Injured,greater_than(0.0),0,-10.0,2004-0294-FJI
26,Column,No. Affected,greater_than(0.0),0,-10.0,1983-0440-PAK
27,Column,No. Homeless,greater_than(0.0),0,-10.0,2011-0368-IRN
28,Column,Total Affected,greater_than(0.0),0,-10.0,2013-0565-CHN
29,Column,Reconstruction Costs ('000 US$),greater_than(0.0),0,-10.0,1990-0508-MEX
32,Column,"Insured Damage, Adjusted ('000 US$)",greater_than(0.0),0,-10.0,1991-0646-PAK
31,Column,Insured Damage ('000 US$),greater_than(0.0),0,-10.0,1978-0057-ITA
1,Column,Classification Key,Invalid classification key,0,wrong_classif_key,1927-0012-DZA
33,Column,Total Damage ('000 US$),greater_than(0.0),0,-10.0,2005-0639-CHN
34,Column,"Total Damage, Adjusted ('000 US$)",greater_than(0.0),0,-10.0,2009-0186-COD
35,Column,CPI,"in_range(0.0, 100.0)",0,101.0,1979-9131-NPL
36,Column,Admin Units,Invalid JSON string,0,wrong_json,1999-0673-IND
37,Column,Entry Date,"in_range(1988-01-01 00:00:00, 2024-08-22 12:55...",0,1987-01-01 00:00:00,2010-0466-RUS
38,Column,Last Update,"in_range(1988-01-01 00:00:00, 2024-08-22 12:55...",0,2100-01-01 00:00:00,1993-0500-CMR
22,Column,End Month,"isin(range(1, 13))",0,-2.0,1998-0261-AUS
0,Column,Historic,"isin(['Yes', 'No'])",0,wrong_historic,1993-0096-DEU
20,Column,Start Day,"isin(range(1, 32))",0,32.0,2002-0492-PNG
19,Column,Start Month,"isin(range(1, 13))",0,13.0,1983-0084-SUN
2,Column,Disaster Group,Invalid group name,0,wrong_group,2019-0275-SRB
3,Column,Disaster Subgroup,Invalid subgroup name,0,wrong_subgroup,2005-0507-LBR
4,Column,Disaster Type,Invalid type name,0,wrong_type,1987-0076-UGA
5,Column,Disaster Subtype,Invalid subtype name,0,wrong_subtype,1993-0292-PHL
6,Column,External IDs,Invalid external ID,0,wrong_id,2002-0231-MYS
7,Column,ISO,Invalid ISO3 code,0,wrong_iso,2011-0120-COL
8,Column,Subregion,Subregions not in reference list,0,wrong_subregion,2003-0608-UKR
9,Column,Region,Regions not in reference list,0,wrong_region,1927-0012-DZA
10,Column,OFDA/BHA Response,"isin(['Yes', 'No'])",0,wrong_response,2019-0008-BRA
11,Column,Appeal,"isin(['Yes', 'No'])",0,wrong_appeal,2015-0525-IRL
12,Column,Declaration,"isin(['Yes', 'No'])",0,wrong_declaration,2004-0285-IRN
13,Column,AID Contribution ('000 US$),greater_than(0.0),0,-500.0,2021-0649-SVN
14,Column,Magnitude,not_equal_to(0.0),0,0.0,2007-0092-LTU
15,Column,Magnitude Scale,Magnitude unit not in reference list,0,wrong_unit,1995-0192-GLP
16,Column,Latitude,"in_range(-90.0, 90.0)",0,91.0,1993-0287-IDN
17,Column,Longitude,"in_range(-180.0, 180.0)",0,181.0,2018-0091-MOZ
18,Column,Start Year,"in_range(1900, 2024)",0,1899,2019-0523-IDN
21,Column,End Year,"in_range(1900, 2024)",0,2100,1981-0106-LKA

## Add Warnings to the Report

In [9]:
from emtest.utils import set_warnings_to_errors
updated_schema = set_warnings_to_errors(emdat_schema)
try:
    updated_schema.validate(emdat, lazy=True)
except pa.errors.SchemaErrors as exc:
    print(f"{len(exc.failure_cases)} failure cases:")
    print(exc.failure_cases)

48 failure cases:
   schema_context                                     column  \
47          Index                                     DisNo.
46          Index                                     DisNo.
45          Index                                     DisNo.
35         Column            Reconstruction Costs ('000 US$)
26         Column                                  Start Day
27         Column                                   End Year
28         Column                                  End Month
29         Column                                    End Day
30         Column                               Total Deaths
31         Column                                No. Injured
32         Column                               No. Affected
33         Column                               No. Homeless
34         Column                             Total Affected
36         Column  Reconstruction Costs, Adjusted ('000 US$)
1          Column                         Classification Key
37         Column                  Insured Damage ('000 US$)
38         Column        Insured Damage, Adjusted ('000 US$)
39         Column                    Total Damage ('000 US$)
40         Column          Total Damage, Adjusted ('000 US$)
41         Column                                        CPI
42         Column                                Admin Units
43         Column                                 Entry Date
44         Column                                Last Update
25         Column                                Start Month
0          Column                                   Historic
23         Column                                  Longitude
11         Column                                    Country
2          Column                             Disaster Group
3          Column                          Disaster Subgroup
4          Column                              Disaster Type
5          Column                           Disaster Subtype
6          Column                               External IDs
7          Column                                        ISO
8          Column                                        ISO
9          Column                                        ISO
10         Column                                        ISO
12         Column                                    Country
22         Column                                   Latitude
13         Column                                    Country
14         Column                                  Subregion
15         Column                                     Region
16         Column                          OFDA/BHA Response
17         Column                                     Appeal
18         Column                                Declaration
19         Column                AID Contribution ('000 US$)
20         Column                                  Magnitude
21         Column                            Magnitude Scale
24         Column                                 Start Year

                                                check check_number  \
47                             Invalid DisNo. Pattern            0
46                                   field_uniqueness         None
45                                   field_uniqueness         None
35                                  greater_than(0.0)            0
26                                 isin(range(1, 32))            0
27                               in_range(1900, 2024)            0
28                                 isin(range(1, 13))            0
29                                 isin(range(1, 32))            0
30                                  greater_than(0.0)            0
31                                  greater_than(0.0)            0
32                                  greater_than(0.0)            0
33                                  greater_than(0.0)            0
34                                  greater_than(0.0)            0
36                                  greater_than(0.0)            0
1                          Invalid classification key            0
37                                  greater_than(0.0)            0
38                                  greater_than(0.0)            0
39                                  greater_than(0.0)            0
40                                  greater_than(0.0)            0
41                               in_range(0.0, 100.0)            0
42                                Invalid JSON string            0
43  in_range(1988-01-01 00:00:00, 2024-08-22 12:55...            0
44  in_range(1988-01-01 00:00:00, 2024-08-22 12:55...            0
25                                 isin(range(1, 13))            0
0                                 isin(['Yes', 'No'])            0
23                            in_range(-180.0, 180.0)            0
11                    Countries not in reference list            0
2                                  Invalid group name            0
3                               Invalid subgroup name            0
4                                   Invalid type name            0
5                                Invalid subtype name            0
6                                 Invalid external ID            0
7                                   Invalid ISO3 code            0
8                     ISO3 code not in reference list            1
9                     ISO3 code not in reference list            1
10                    ISO3 code not in reference list            1
12                    Countries not in reference list            0
22                              in_range(-90.0, 90.0)            0
13                    Countries not in reference list            0
14                   Subregions not in reference list            0
15                      Regions not in reference list            0
16                                isin(['Yes', 'No'])            0
17                                isin(['Yes', 'No'])            0
18                                isin(['Yes', 'No'])            0
19                                  greater_than(0.0)            0
20                                  not_equal_to(0.0)            0
21               Magnitude unit not in reference list            0
24                               in_range(1900, 2024)            0

                  failure_case          index
47                 wrong_disno              0
46               1927-0012-DZA             11
45               1927-0012-DZA              2
35                       -10.0  1990-0508-MEX
26                        32.0  2002-0492-PNG
27                        2100  1981-0106-LKA
28                        -2.0  1998-0261-AUS
29                        12.5  1990-0630-IND
30                       -10.0  2013-0259-CHN
31                       -10.0  2004-0294-FJI
32                       -10.0  1983-0440-PAK
33                       -10.0  2011-0368-IRN
34                       -10.0  2013-0565-CHN
36                       -10.0  2009-0122-CHN
1            wrong_classif_key  1927-0012-DZA
37                       -10.0  1978-0057-ITA
38                       -10.0  1991-0646-PAK
39                       -10.0  2005-0639-CHN
40                       -10.0  2009-0186-COD
41                       101.0  1979-9131-NPL
42                  wrong_json  1999-0673-IND
43         1987-01-01 00:00:00  2010-0466-RUS
44         2100-01-01 00:00:00  1993-0500-CMR
25                        13.0  1983-0084-SUN
0               wrong_historic  1993-0096-DEU
23                       181.0  2018-0091-MOZ
11               wrong_country  1991-0372-IND
2                  wrong_group  2019-0275-SRB
3               wrong_subgroup  2005-0507-LBR
4                   wrong_type  1987-0076-UGA
5                wrong_subtype  1993-0292-PHL
6                     wrong_id  2002-0231-MYS
7                    wrong_iso  2011-0120-COL
8                    wrong_iso  2011-0120-COL
9                          SUN  1983-0084-SUN
10                         TWN  2002-0415-TWN
12                Soviet Union  1983-0084-SUN
22                        91.0  1993-0287-IDN
13  Taiwan (Province of China)  2002-0415-TWN
14             wrong_subregion  2003-0608-UKR
15                wrong_region  1927-0012-DZA
16              wrong_response  2019-0008-BRA
17                wrong_appeal  2015-0525-IRL
18           wrong_declaration  2004-0285-IRN
19                      -500.0  2021-0649-SVN
20                         0.0  2007-0092-LTU
21                  wrong_unit  1995-0192-GLP
24                        1899  2019-0523-IDN

In [10]:
get_validation_report(emdat, emdat_schema, add_warnings=True)

,schema_context,column,check,check_number,failure_case,index
47,Index,DisNo.,Invalid DisNo. Pattern,0,wrong_disno,0
46,Index,DisNo.,field_uniqueness,None,1927-0012-DZA,11
45,Index,DisNo.,field_uniqueness,None,1927-0012-DZA,2
35,Column,Reconstruction Costs ('000 US$),greater_than(0.0),0,-10.0,1990-0508-MEX
26,Column,Start Day,"isin(range(1, 32))",0,32.0,2002-0492-PNG
27,Column,End Year,"in_range(1900, 2024)",0,2100,1981-0106-LKA
28,Column,End Month,"isin(range(1, 13))",0,-2.0,1998-0261-AUS
29,Column,End Day,"isin(range(1, 32))",0,12.5,1990-0630-IND
30,Column,Total Deaths,greater_than(0.0),0,-10.0,2013-0259-CHN
31,Column,No. Injured,greater_than(0.0),0,-10.0,2004-0294-FJI
32,Column,No. Affected,greater_than(0.0),0,-10.0,1983-0440-PAK
33,Column,No. Homeless,greater_than(0.0),0,-10.0,2011-0368-IRN
34,Column,Total Affected,greater_than(0.0),0,-10.0,2013-0565-CHN
36,Column,"Reconstruction Costs, Adjusted ('000 US$)",greater_than(0.0),0,-10.0,2009-0122-CHN
1,Column,Classification Key,Invalid classification key,0,wrong_classif_key,1927-0012-DZA
37,Column,Insured Damage ('000 US$),greater_than(0.0),0,-10.0,1978-0057-ITA
38,Column,"Insured Damage, Adjusted ('000 US$)",greater_than(0.0),0,-10.0,1991-0646-PAK
39,Column,Total Damage ('000 US$),greater_than(0.0),0,-10.0,2005-0639-CHN
40,Column,"Total Damage, Adjusted ('000 US$)",greater_than(0.0),0,-10.0,2009-0186-COD
41,Column,CPI,"in_range(0.0, 100.0)",0,101.0,1979-9131-NPL
42,Column,Admin Units,Invalid JSON string,0,wrong_json,1999-0673-IND
43,Column,Entry Date,"in_range(1988-01-01 00:00:00, 2024-08-22 12:55...",0,1987-01-01 00:00:00,2010-0466-RUS
44,Column,Last Update,"in_range(1988-01-01 00:00:00, 2024-08-22 12:55...",0,2100-01-01 00:00:00,1993-0500-CMR
25,Column,Start Month,"isin(range(1, 13))",0,13.0,1983-0084-SUN
0,Column,Historic,"isin(['Yes', 'No'])",0,wrong_historic,1993-0096-DEU
23,Column,Longitude,"in_range(-180.0, 180.0)",0,181.0,2018-0091-MOZ
11,Column,Country,Countries not in reference list,0,wrong_country,1991-0372-IND
2,Column,Disaster Group,Invalid group name,0,wrong_group,2019-0275-SRB
3,Column,Disaster Subgroup,Invalid subgroup name,0,wrong_subgroup,2005-0507-LBR
4,Column,Disaster Type,Invalid type name,0,wrong_type,1987-0076-UGA
5,Column,Disaster Subtype,Invalid subtype name,0,wrong_subtype,1993-0292-PHL
6,Column,External IDs,Invalid external ID,0,wrong_id,2002-0231-MYS
7,Column,ISO,Invalid ISO3 code,0,wrong_iso,2011-0120-COL
8,Column,ISO,ISO3 code not in reference list,1,wrong_iso,2011-0120-COL
9,Column,ISO,ISO3 code not in reference list,1,SUN,1983-0084-SUN
10,Column,ISO,ISO3 code not in reference list,1,TWN,2002-0415-TWN
12,Column,Country,Countries not in reference list,0,Soviet Union,1983-0084-SUN
22,Column,Latitude,"in_range(-90.0, 90.0)",0,91.0,1993-0287-IDN
13,Column,Country,Countries not in reference list,0,Taiwan (Province of China),2002-0415-TWN
14,Column,Subregion,Subregions not in reference list,0,wrong_subregion,2003-0608-UKR
15,Column,Region,Regions not in reference list,0,wrong_region,1927-0012-DZA
16,Column,OFDA/BHA Response,"isin(['Yes', 'No'])",0,wrong_response,2019-0008-BRA
17,Column,Appeal,"isin(['Yes', 'No'])",0,wrong_appeal,2015-0525-IRL
18,Column,Declaration,"isin(['Yes', 'No'])",0,wrong_declaration,2004-0285-IRN
19,Column,AID Contribution ('000 US$),greater_than(0.0),0,-500.0,2021-0649-SVN
20,Column,Magnitude,not_equal_to(0.0),0,0.0,2007-0092-LTU
21,Column,Magnitude Scale,Magnitude unit not in reference list,0,wrong_unit,1995-0192-GLP
24,Column,Start Year,"in_range(1900, 2024)",0,1899,2019-0523-IDN

## Type-specific Schemas

In [13]:
from emtest import earthquake_schema

emdat_eq = emdat[emdat['Disaster Type'] == 'Earthquake']

get_validation_report(emdat_eq, earthquake_schema)

,schema_context,column,check,check_number,failure_case,index
3,Index,DisNo.,Invalid DisNo. Pattern,0,wrong_disno,0
0,Column,Magnitude,Invalid earthquake magnitude,0,5.7,1978-0057-ITA
1,Column,Magnitude,Invalid earthquake magnitude,0,5.6,2022-0231-BIH
2,Column,Insured Damage ('000 US$),greater_than(0.0),0,-10.0,1978-0057-ITA

## Customize Columns' Checks

In [12]:
from emtest.utils import update_column_checks
coldwave_schema = update_column_checks(
    schema=emdat_schema,
    col_name='Magnitude',
    new_checks=[
        pa.Check.less_than(
            max_value=0,
            description="Test whether value is between 6 and 10",
            name="check_coldwave_magnitude",
            error="Invalid coldwave magnitude"
        )
    ]
)

In [14]:
emdat_cw = emdat[emdat['Disaster Subtype'] == 'Cold wave']
get_validation_report(emdat_cw, coldwave_schema)

,schema_context,column,check,check_number,failure_case,index
0,Column,Magnitude,Invalid coldwave magnitude,0,10.0,1986-0015-CHN